### ISSUE TITLE
Consider adding seng generator as a local dependency

### ISSUE THREAD

**Issue by skulptur** [mediamonks/muban#107]
Currently we're asking devs to install seng generator globaly. This can be inconvenient when setting up new machines or when we need to code in other machines. We should consider adding seng generator as a dependency and adding a new script to the package.json, for example: `"generate": "sg wizard"`.

**Comment by flut1** [comment]
In my opinion we shouldn't add dependencies if we happen to use them often but they are otherwise unrelated to Muban. This way users of Muban are free to pick whatever 'generator-like tooling' they prefer. In my view:

-  If you use seng-generator as a personal convenience, you should not add package.json scripts and install `sg` globally.
- If you want to setup seng-generator as a convenience for your project, you should add the dependency _and_ a package.json script to just that project. This will also encourage you to add custom `sg` commands that are tailored to your project, rather than having a generic `sg wizard` everywhere.

Just my personal opinion. I'm open to alternative suggestions.

**Comment by skulptur** [comment]
I get your point and I personally use other tools to generate code in my own projects. However since Muban already comes with the templates for seng generator it seems like a disconnect to not include the tool to make those templates work.

**Comment by flut1** [comment]
Ah I didn't realize that Muban already comes with templates. In that case I agree with you that does seem like a bit of a disconnect. It might even be a good idea from a technical standpoint, just in case sg ever gets a major upgrade with a breaking change that's incompatible with the templates in Muban
