### ISSUE TITLE
Building requires yaml file extension for data included in pages

### ISSUE THREAD

**Issue by pigeonfresh** [mediamonks/muban#40]
Maybe unrelated but having a second include of a block in a page with different data requires the .yaml extension for all of the data when building. During runtime there is no issue at all. Having the yaml files in the root of the block doesn't fix it.

  - name: "hero-general"
    data: "import!../app/component/block/hero-general/data/data.yaml"
    
  - name: "hero-general"
    data: "import!../app/component/block/hero-general/data/variation.yaml"

**Comment by ThaNarie** [comment]
Yeah, extension-less works in webpack during dev because of auto resolve extensions, but node can't do that (only supports `.js` and `.json`).
Main reason of the error is that without extension, it cannot determine which parser to use.

So to mimic the webpack way, I could try to check the file with the extensions from the all supported resolvers, and if one matches I set the extension to that one.

**Comment by pigeonfresh** [comment]
This has been fixed
