### ISSUE TITLE
Add option to use ES6, ES7

### ISSUE THREAD

**Issue by thanhnhan2tn** [mediamonks/muban#42]
This is a nice template, 
But the limits are using TypeScript, The TypeScript is really new with almost user and needs more time to learn.
So please add an option to use ES @pigeonfresh .

**Comment by ThaNarie** [comment]
Hi @thanhnhan2tn!

Muban supports both JS and TS fully, so you can choose which files you want as JavaScript or TypeScript. The only difference is that TS files are first converted from TS to ES+ before they are run through babel.

I noticed a conflict due to the `transform-class-display-name` babel transform that was included but not needed at all, so the last commit in master should address that issue.
