### ISSUE TITLE
Importing Google Web Fonts breaks the rendering of the components 

### ISSUE THREAD

**Issue by mmmilgron** [mediamonks/muban#91]
Browser: Google Chrome
Server mode: Development server mode

When an import is made by the scss file (Google font in this case), the rendering of the components doesn't succeed. If the browser reloads several times, sometimes the components are rendered. 

In Safari and Firefox works fine.

**Comment by larsvanbraam** [comment]
We noticed this issue last week and it related to the [waitForStyleSheetsLoaded](https://github.com/mediamonks/muban-core/blob/master/src/lib/utils/waitForStyleSheetsLoaded.ts) util. When the Google font import is added to the stylesheet it fails to complete and stays in `pending` mode. A quick workaround would be to to add the `<link>` to the `<head>` instead of the import to the `font.scss` 

@ThaNarie was looking into this last week but i'm not sure what the current status is on this!

**Comment by ThaNarie** [comment]
@mmmilgron Could you try updating muban-core to 1.13.1 in your project and see if that solves your issue, and doesn't break anything else regarding that loading check?
Thanks!

**Comment by mmmilgron** [comment]
I upload to the muban-core@1.13.1 and now is working fine :) 
Thanks!
